name: PopUpWindow
author: jplarson
category: Interface
tags: [widget, popup, window]
docs: http://github.com/jplarson/PopUpWindow/blob/master/README.md
demo: http://www.jpl-consulting.com/projects/MooTools/PopUpWindow/Demo/